<a href="https://colab.research.google.com/github/Greeshma-S-Kunder/AmlPrograms/blob/main/AmlLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Activity 1 :
import numpy as np

a = np.array([1,2,23, 34])
print(a)

b = np.arange(1, 23)
print(b)

c = np.linspace(0,1,6)
print(c)

[ 1  2 23 34]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
[0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
#Activity 2 : Matrix Operation
A = np.array([[1,2], [3,4]])

B = np.array([[5,6], [7,8]])

print(A - B)
print(A + B)
print(A * B)
print(A @ B)

[[-4 -4]
 [-4 -4]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
#Activity 3 : Statistics

marks = np.array([45, 67, 98, 56, 34, 80])

print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.std(marks))


63.333333333333336
98
34
21.38275525329283


In [ ]:
#Assignment 1 : weather data of last 10 days or 1 month of udupi , and find which is hottestand coldest day
#and calculate average temp of overall city and find whilch all days are above 35 degree celsius

import pandas as pd
import numpy as np

path = 'weather.csv'

df1=pd.read_csv(path)

#weather data of last 1 month in jan
''' for Month in df1:
  if Month == 1 :
    print(df1) '''

print(df1['Data.Temperature.Min Temp'])





0        32
1        31
2        41
3        38
4        29
         ..
16738    15
16739    21
16740     4
16741    13
16742     8
Name: Data.Temperature.Min Temp, Length: 16743, dtype: int64


In [ ]:
import numpy as np

temp_array = np.array([23.4, 23.7, 45, 46,50.2, 34, 35.6, 35.6, 67.8, 46.3])

hottest_day = np.max(temp_array)
coldest_day = np.min(temp_array)
print("The hottest temperature recorded is :" , hottest_day)
print("The hottest temperature recorded is :" , coldest_day)

print("The temperatures above 35 degree is given below: ")

for item in temp_array:
  if(item > 35):
    print(item)


The hottest temperature recorded is : 67.8
The hottest temperature recorded is : 23.4
The temperatures above 35 degree is given below: 
45.0
46.0
50.2
35.6
35.6
67.8
46.3


In [ ]:
#Activity 1 : Create a Dataframe
import pandas as pd

Student_name = {"Name" : ["Greeshma", "Usha", "hima"], "place" : ["Udupi", "shivamoga", "bangalore"],
"Marks" : ["90","90", "90"]   }

data_frame1 = pd.DataFrame(Student_name)

data_frame1


,Name,place,Marks
0,Greeshma,Udupi,90
1,Usha,shivamoga,90
2,hima,bangalore,90


In [ ]:
#Activity 2 : Reading datasets
from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)

data_frame = iris.frame

data_frame.head()



,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [ ]:
#Activity : 3

data_frame.info()
data_frame.describe()
data_frame.shape
data_frame.columns
data_frame.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2


In [ ]:
#Activity 4 : Selecting data

data_frame[['sepal length (cm)', 'target']]
data_frame.iloc[:5]
data_frame.loc[10:20]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
10,5.4,3.7,1.5,0.2,0
11,4.8,3.4,1.6,0.2,0
12,4.8,3.0,1.4,0.1,0
13,4.3,3.0,1.1,0.1,0
14,5.8,4.0,1.2,0.2,0
15,5.7,4.4,1.5,0.4,0
16,5.4,3.9,1.3,0.4,0
17,5.1,3.5,1.4,0.3,0
18,5.7,3.8,1.7,0.3,0
19,5.1,3.8,1.5,0.3,0


In [ ]:
#Activity 5 : Searching the data
data_frame[data_frame['target']==1]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
50,7.0,3.2,4.7,1.4,1
51,6.4,3.2,4.5,1.5,1
52,6.9,3.1,4.9,1.5,1
53,5.5,2.3,4.0,1.3,1
54,6.5,2.8,4.6,1.5,1
55,5.7,2.8,4.5,1.3,1
56,6.3,3.3,4.7,1.6,1
57,4.9,2.4,3.3,1.0,1
58,6.6,2.9,4.6,1.3,1
59,5.2,2.7,3.9,1.4,1


In [ ]:
#Activity 6 : Sorting
data_frame.sort_values(by = 'sepal length (cm)')

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
13,4.3,3.0,1.1,0.1,0
8,4.4,2.9,1.4,0.2,0
42,4.4,3.2,1.3,0.2,0
38,4.4,3.0,1.3,0.2,0
41,4.5,2.3,1.3,0.3,0
...,...,...,...,...,...
122,7.7,2.8,6.7,2.0,2
117,7.7,3.8,6.7,2.2,2
118,7.7,2.6,6.9,2.3,2
135,7.7,3.0,6.1,2.3,2


In [ ]:
#1.find the titanic dataset online or github
#2.find total number of passengers
#3.find the average age of surviors and non surviors
#4.list the passengers who are older than 60 years
#5.find the avg fare for each passenger class

import numpy as np
import pandas as pd

url = pd.read_csv('titanic.csv')
df = pd.DataFrame(url)

#finding the total number of passengers
print("The total Number of passengers : ",df['PassengerId'].count())
print("\n")

#find the average age of surviors and non surviors
df['survived_num'] = df['Survived']==1
print("The Average age of survivors:")
print(df.groupby('survived_num')['Age'].mean())
print("\n")

#without using groupby
print("The average age of non survivors : ")
non_survivors = df[~(df['survived_num'])]
print(non_survivors['Age'].mean())
print("\n")

#list the passengers who are older than 60 years
print("The list of passengers who are older than 60 years of age :")
print(df[(df['Age'] > 60)][['PassengerId','Name', 'Age', 'Sex']])
print("\n")

#find the avg fare for each passenger class
print(df.groupby('Pclass')['Fare'].mean())



The total Number of passengers :  891


The Average age of survivors:
survived_num
False    30.626179
True     28.343690
Name: Age, dtype: float64


The average age of non survivors : 
30.62617924528302


The list of passengers who are older than 60 years of age :
     PassengerId                                       Name   Age     Sex
33            34                      Wheadon, Mr. Edward H  66.0    male
54            55             Ostby, Mr. Engelhart Cornelius  65.0    male
96            97                  Goldschmidt, Mr. George B  71.0    male
116          117                       Connors, Mr. Patrick  70.5    male
170          171                  Van der hoef, Mr. Wyckoff  61.0    male
252          253                  Stead, Mr. William Thomas  62.0    male
275          276          Andrews, Miss. Kornelia Theodosia  63.0  female
280          281                           Duane, Mr. Frank  65.0    male
326          327                  Nysveen, Mr. Johan Hansen  61.0    

In [ ]:
df


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,survived_num
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,True
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,True
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,False
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,True
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,False
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,True
